# Configuration file for Smart Dustbin

# WiFi Credentials
WIFI_SSID = "sheykhonieRPW"
WIFI_PASSWORD = "h4rdm34n"

# Bin Settings
BIN_HEIGHT = 40
FULL_THRESHOLD = 80
HALF_THRESHOLD = 50

# Sensor Settings
LID_TRIGGER_DISTANCE = 30
LID_OPEN_TIME = 5
SENSOR_TIMEOUT = 30000

# Pin Assignments
LID_SENSOR_TRIG = 2
LID_SENSOR_ECHO = 3
FILL_SENSOR_TRIG = 4
FILL_SENSOR_ECHO = 5
SERVO_PIN = 15
LED_GREEN = 16
LED_YELLOW = 17
LED_RED = 18
BUZZER_PIN = 19

# Servo Settings
SERVO_FREQ = 50
SERVO_CLOSED_DUTY = 2500
SERVO_OPEN_DUTY = 7500
